export const PORTFOLIO_DATA = {
  en: [
    {
      id: 'ai',
      theme: 'AI Engineering',
      accent: '#3b82f6',
      description: 'Language models, cognitive systems, and intelligent infrastructure.',
      projects: [
        {
          id: 'obelysk',
          title: 'Obelysk',
          subtitle: 'Cognitive infrastructure and SLMs for Latin America.',
          image: '/images/sml-hero.jpg',
          date: 'May 2026',
          author: 'rodgmont',
          views: 0,
          shares: 0,
          tags: ['AI Engineering', 'LLMOps', 'Infrastructure'],
          link: 'https://www.obelysk.tech/',
          body: 'Architecting and building the core infrastructure for deploying small language models (SLMs) tailored for resource-constrained environments. The focus is on lowering inference latency and making advanced AI accessible to organizations across Latin America and beyond.',
        },
        {
          id: 'haiku',
          title: 'HAIKU',
          subtitle: 'AI-powered adaptive learning engine.',
          image: '/images/obelysk-hero.jpg',
          date: 'Apr 2026',
          author: 'rodgmont',
          views: 0,
          shares: 0,
          tags: ['Machine Learning', 'EdTech', 'Backend'],
          link: '#',
          body: 'An adaptive learning platform combining educational pedagogy with personalized ML models. The backend dynamically adjusts curriculum difficulty based on real-time student performance data, enabling a truly personalized learning experience.',
        },
      ],
    },
    {
      id: 'engineering',
      theme: 'Software Engineering',
      accent: '#f59e0b',
      description: 'Systems, data pipelines, and backend architecture.',
      projects: [
        {
          id: 'analytics-pipeline',
          title: 'Analytics Pipeline',
          subtitle: 'High-throughput on-chain data processing system.',
          image: '/images/obelysk-hero.jpg',
          date: 'Mar 2026',
          author: 'rodgmont',
          views: 0,
          shares: 0,
          tags: ['Data Engineering', 'Go', 'Blockchain'],
          link: '#',
          body: 'A high-throughput data pipeline to process and analyze on-chain data in real-time, applying heuristic-based anomaly detection algorithms to identify specific transaction patterns and potential risks before confirmation.',
        },
      ],
    },
    {
      id: 'opensource',
      theme: 'Open Source',
      accent: '#10b981',
      description: 'Contributions to the open-source ecosystem.',
      projects: [
        {
          id: 'ai-optimization',
          title: 'AI Model Optimization',
          subtitle: 'Quantization tools for transformer models.',
          image: '/images/sml-hero.jpg',
          date: 'Feb 2026',
          author: 'rodgmont',
          views: 0,
          shares: 0,
          tags: ['Open Source', 'PyTorch', 'Transformers'],
          link: 'https://github.com/rodgmont',
          body: 'Contributions to open-source libraries focused on quantizing and fine-tuning transformer models. Improved documentation and added support for novel hardware architectures to make model optimization more accessible.',
        },
      ],
    },
    {
      id: 'research',
      theme: 'Research',
      accent: '#8b5cf6',
      description: 'Papers, technical essays, and public investigations.',
      projects: [
        {
          id: 'slms-latam',
          title: 'SLMs for Latin America?',
          subtitle: 'Why smart language models are the right bet for the region.',
          image: '/images/sml-hero.jpg',
          date: 'May 2026',
          author: 'rodgmont',
          views: 1,
          shares: 0,
          tags: ['Research', 'AI', 'Ideas'],
          link: '/blog/smart-language-models',
          body: 'An analysis of how small language models can bridge the AI gap in Latin America, examining infrastructure constraints, language barriers, and economic realities that make SLMs a more viable path than large frontier models for the region.',
        },
      ],
    },
  ],
  es: [
    {
      id: 'ai',
      theme: 'Ingeniería de IA',
      accent: '#3b82f6',
      description: 'Modelos de lenguaje, sistemas cognitivos e infraestructura inteligente.',
      projects: [
        {
          id: 'obelysk',
          title: 'Obelysk',
          subtitle: 'Infraestructura cognitiva y SLMs para América Latina.',
          image: '/images/sml-hero.jpg',
          date: 'Mayo 2026',
          author: 'rodgmont',
          views: 0,
          shares: 0,
          tags: ['Ingeniería de IA', 'LLMOps', 'Infraestructura'],
          link: 'https://www.obelysk.tech/',
          body: 'Arquitectura y desarrollo de la infraestructura central para desplegar modelos de lenguaje pequeños (SLMs) optimizados para entornos con recursos limitados. El enfoque está en reducir la latencia de inferencia y hacer la IA avanzada accesible a organizaciones en toda América Latina.',
        },
        {
          id: 'haiku',
          title: 'HAIKU',
          subtitle: 'Motor de aprendizaje adaptativo impulsado por IA.',
          image: '/images/obelysk-hero.jpg',
          date: 'Abr 2026',
          author: 'rodgmont',
          views: 0,
          shares: 0,
          tags: ['Machine Learning', 'EdTech', 'Backend'],
          link: '#',
          body: 'Una plataforma de aprendizaje adaptativo que combina pedagogía educativa con modelos de ML personalizados. El backend ajusta dinámicamente la dificultad del currículo basándose en el rendimiento del estudiante en tiempo real.',
        },
      ],
    },
    {
      id: 'engineering',
      theme: 'Ingeniería de Software',
      accent: '#f59e0b',
      description: 'Sistemas, pipelines de datos y arquitectura backend.',
      projects: [
        {
          id: 'analytics-pipeline',
          title: 'Pipeline de Analítica',
          subtitle: 'Sistema de procesamiento de datos on-chain de alto rendimiento.',
          image: '/images/obelysk-hero.jpg',
          date: 'Mar 2026',
          author: 'rodgmont',
          views: 0,
          shares: 0,
          tags: ['Ingeniería de Datos', 'Go', 'Blockchain'],
          link: '#',
          body: 'Un pipeline de datos de alto rendimiento para procesar y analizar datos on-chain en tiempo real, aplicando algoritmos de detección de anomalías basados en heurísticas para identificar patrones de transacciones específicos.',
        },
      ],
    },
    {
      id: 'opensource',
      theme: 'Open Source',
      accent: '#10b981',
      description: 'Contribuciones al ecosistema open-source.',
      projects: [
        {
          id: 'ai-optimization',
          title: 'Optimización de Modelos de IA',
          subtitle: 'Herramientas de cuantización para modelos transformer.',
          image: '/images/sml-hero.jpg',
          date: 'Feb 2026',
          author: 'rodgmont',
          views: 0,
          shares: 0,
          tags: ['Open Source', 'PyTorch', 'Transformers'],
          link: 'https://github.com/rodgmont',
          body: 'Contribuciones a librerías open-source enfocadas en cuantización y fine-tuning de modelos transformer. Mejora de documentación y soporte para nuevas arquitecturas de hardware.',
        },
      ],
    },
    {
      id: 'research',
      theme: 'Investigaciones',
      accent: '#8b5cf6',
      description: 'Papers, ensayos técnicos e investigaciones públicas.',
      projects: [
        {
          id: 'slms-latam',
          title: '¿SLMs para Latinoamérica?',
          subtitle: 'Por qué los modelos de lenguaje inteligentes son la apuesta correcta para la región.',
          image: '/images/sml-hero.jpg',
          date: 'Mayo 2026',
          author: 'rodgmont',
          views: 1,
          shares: 0,
          tags: ['Investigación', 'IA', 'Ideas'],
          link: '/es/blog/smart-language-models',
          body: 'Un análisis de cómo los modelos de lenguaje pequeños pueden cerrar la brecha de IA en América Latina, examinando las limitaciones de infraestructura, barreras lingüísticas y realidades económicas que hacen de los SLMs una alternativa más viable que los grandes modelos de frontera.',
        },
      ],
    },
  ],
};

export function getPortfolioData(locale) {
  return PORTFOLIO_DATA[locale] ?? PORTFOLIO_DATA.en;
}
